name: Crosstools NG

on:
  push:
    branches:
      - master

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: $GITHUB_ACTOR
          password: $GITHUB_TOKEN
          registry: docker.pkg.github.com
          repository: $GITHUB_REPOSITORY/docker-ct-ng
          tags: ${{steps.date.outputs.date}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
