name: Crosstools NG

on:
  push:
    branches:
      - master

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/ct-ng
          tags: ${{steps.date.outputs.date}},latest

  build_toolchains:
    needs: build_docker_image
    runs-on: ubuntu-latest

    env:
      CONTAINER_IMAGE: docker.pkg.github.com/${{ github.repository }}/ct-ng:latest
      GITHUB_TOKEN: ${{ secrets.GTOKEN }}

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN

      - name: Pull Docker image with crosstools-ng
        run: docker pull "$CONTAINER_IMAGE"

      - name: Run ct-ng build
        run: |
          mkdir -p $GITHUB_WORKSPACE/x-tools
          chmod o+rwx $GITHUB_WORKSPACE/x-tools
          docker run -v $GITHUB_WORKSPACE/x-tools:/home/build/x-tools $CONTAINER_IMAGE arm-unknown-linux-musleabi

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create release
        id: create_release
        # use branch due to opened issue
        # https://github.com/actions/create-release/pull/12
        uses: vicr123/create-release@delete-old-release
        with:
          replace_old_tag: true
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./x-tools/arm-unknown-linux-musleabi.tar.xz
          asset_name: arm-unknown-linux-musleabi.tar.xz
          asset_content_type: application/x-tar
