name: Crosstools NG

on:
  push:
    branches:
      - master

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/ct-ng
          tags: ${{steps.date.outputs.date}},latest

  build_toolchains:
    needs: build_docker_image
    runs-on: ubuntu-latest

    env:
      CONTAINER_IMAGE: docker.pkg.github.com/${{ github.repository }}/ct-ng:latest

    steps:
      - uses: actions/checkout@v1

      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Pull Docker image
        run: docker pull "$CONTAINER_IMAGE"

      - name: Run image
        run: |
          mkdir -p $GITHUB_WORKSPACE/x-tools
          chmod o+rwx $GITHUB_WORKSPACE/x-tools
          docker run -v $GITHUB_WORKSPACE/x-tools:/home/build/x-tools $CONTAINER_IMAGE arm-unknown-linux-musleabi

      - name: Pack zip archive
        run: mkdir output ; zip output/arm-unknown-linux-musleabi.zip $GITHUB_WORKSPACE/x-tools/arm-unknown-linux-musleabi/*

      - uses: actions/upload-artifact@v2
        with:
          name: arm-unknown-linux-musleabi
          path: output/arm-unknown-linux-musleabi.zip
